Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Web.Mvc;
using TutionClass.DBConnection;
using TutionClass.Models;

namespace TutionClass.Controllers
{
    public class ClassController : Controller
    {
        // GET: Class
        public ActionResult Index()
        {
            if (Session["AdminAccessed"] == null)
            {
                Response.Redirect("~/Access"); // Redirect to login page
            }
            List<Class> classList = Class.GetClasses();
            return View(classList);
        }

        public ActionResult AddClass()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Class classObj)
        {
            try
            {
                classObj.AddClass(classObj);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error adding class: " + ex.Message;
                return View("AddClass", classObj);
            }
        }

        [HttpPost]
        public ActionResult Delete(string subjectName, int grade)
        {
            try
            {
                Class.DeleteClass(subjectName, grade);
                ViewBag.Message = "Class deleted successfully!";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error deleting class: " + ex.Message;
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TutionClass.Models;

namespace TutionClass.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult Index()
        {
            if (Session["AdminAccessed"] == null)
            {
                Response.Redirect("~/Access"); // Redirect to login page
            }
            List<Payment> payments = Payment.GetAllPayments();
            return View(payments);
        }

        public ActionResult AddPayment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Payment payment)
        {

            payment.CreatePayment();                
            
            
            return View("AddPayment", payment);
        }
    }
}

Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TutionClass.Models;

namespace TutionClass.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            if (Session["AdminAccessed"] == null)
            {
                Response.Redirect("~/Access"); // Redirect to login page
            }
            ViewBag.Subjects = Class.GetUniqueSubjects();
            return View();
        }
        [HttpPost]
        public ActionResult Generate(ReportFilterViewModel filter)
        {
            // Assuming you have methods to get class information and payments based on filter
            // ReportViewModel should contain the required data for the report view
            ReportViewModel report = new ReportViewModel();
            report.ClassInfo = Class.GetClass(filter.SubjectName, filter.Grade);
            report.Payments = Payment.GetPayments(filter.SubjectName, filter.Grade);

            return View(report);
        }
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Class management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Students", "../Student", "Student")</li>
                    <li>@Html.ActionLink("Classes", "../Class", "Class")</li>
                    <li>@Html.ActionLink("Payments", "../Payment", "Payment")</li>
                    <li>@Html.ActionLink("Reports", "../Report", "Report")</li>
                    <li>@Html.ActionLink("Logout", "../Access/Logout", "Logout")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>